SELECT * FROM [dbo].[WorkNorm];
SELECT * FROM [dbo].[Account];
SELECT * FROM [dbo].[Employee];
SELECT * FROM [dbo].[Department];
SELECT * FROM [dbo].[Skill];
SELECT * FROM [dbo].[Project];
SELECT * FROM [dbo].[TaskItem];
SELECT * FROM [dbo].[Allocation];
SELECT * FROM [dbo].[Timesheet];